const fullmeterMoviePopups = {
  "Fullmeter-Movie_Avatar": [
    {
      nameRu: "Аватар",
      nameEn: "Avatar",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240534?t=16m20s"],
      id: "Fullmeter-Movie_Avatar_1",
      posterImage: "https://static.tildacdn.com/tild3238-3762-4661-b735-306462616438/_Avatar_1.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Путь воды || Аватар",
      nameEn: "The Way of Water || Avatar",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241241?t=11m56s"],
      id: "Fullmeter-Movie_Avatar_2",
      posterImage: "https://static.tildacdn.com/tild6634-3365-4664-a530-623062613936/_Avatar_2.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Johnny-English": [
    {
      nameRu: "Джонни Инглиш",
      nameEn: "Johnny English",
      titleLink: ["boosty", "godenname/posts/304e8e21-55cd-474a-a6d1-2206898ecd22?t=16761&tmid=14f8a96a-9049-42eb-9507-96b1d90b0735"],
      id: "Fullmeter-Movie_Johnny-English_1",
      posterImage: "https://static.tildacdn.com/tild3763-6437-4931-b030-626665373435/_Johnny_English_1.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Перезагрузка || Джонни Инглиш",
      nameEn: "Reborn || Johnny English",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239961?t=4h38m7s"],
      id: "Fullmeter-Movie_Johnny-English_2",
      posterImage: "https://static.tildacdn.com/tild6364-3734-4833-b461-373638323666/_Johnny_English_2.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Alice-in-Wonderland": [
    {
      nameRu: "Алиса в Стране чудес",
      nameEn: "Alice in Wonderland",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241679?t=12m14s"],
      id: "Fullmeter-Movie_Alice-in-Wonderland-1",
      posterImage: "https://static.tildacdn.com/tild3362-3863-4863-b938-313638636535/_Alice_in_Wonderland.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Алиса в Зазеркалье",
      nameEn: "Alice Through the Looking Glass",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241708?t=2h17m51s"],
      id: "Fullmeter-Movie_Alice-in-Wonderland-2",
      posterImage: "https://static.tildacdn.com/tild3331-3965-4465-b236-383836326632/_Alice_in_Wonderland.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Maze-Runner": [
    {
      nameRu: "Бегущий в лабиринте",
      nameEn: "The Maze Runner",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241037?t=14m10s"],
      id: "Fullmeter-Movie_Maze-Runner_1",
      posterImage: "https://static.tildacdn.com/tild3131-6235-4230-a138-653237383031/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Испытание огнём || Бегущий в лабиринте",
      nameEn: "The Scorch Trials || The Maze Runner",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241078?t=5m42s"],
      id: "Fullmeter-Movie_Maze-Runner_2",
      posterImage: "https://static.tildacdn.com/tild6537-6338-4637-a237-306362353863/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Лекарство от смерти || Бегущий в лабиринте",
      nameEn: "The Death Cure || The Maze Runner",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241102?t=13m46s"],
      id: "Fullmeter-Movie_Maze-Runner_3",
      posterImage: "https://static.tildacdn.com/tild6666-6439-4131-b263-616261386136/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Blade-Runner": [
    {
      nameRu: "Бегущий по лезвию 2019",
      nameEn: "Blade Runner",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241465?t=2h13m4s"],
      id: "Fullmeter-Movie_Blade-Runner-1",
      posterImage: "https://static.tildacdn.com/tild6239-6630-4564-b631-613566663032/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Бегущий по лезвию 2049",
      nameEn: "Blade Runner 2049",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241484?t=2h17m45s"],
      id: "Fullmeter-Movie_Blade-Runner-2",
      posterImage: "https://static.tildacdn.com/tild3135-3639-4934-a133-393265366236/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Lord-of-the-Rings": [
    {
      nameRu: "Братство кольца || Властелин колец",
      nameEn: "The Fellowship of the Ring || The Lord of the Rings",
      titleLink: ["vk", "video-208448461_456239220?t=17m35s"],
      id: "Fullmeter-Movie_Lord-of-the-Rings_1",
      posterImage: "https://static.tildacdn.com/tild6264-6465-4237-b838-353839656432/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Две крепости || Властелин колец",
      nameEn: "The Two Towers || The Lord of the Rings",
      titleLink: ["vk", "video-208448461_456239221?t=10m13s"],
      id: "Fullmeter-Movie_Lord-of-the-Rings_2",
      posterImage: "https://static.tildacdn.com/tild3566-3532-4730-a333-623832633033/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Возвращение короля || Властелин колец",
      nameEn: "The Return of the King || The Lord of the Rings",
      titleLink: ["vk", "video-208448461_456239221?t=4h22m3s"],
      id: "Fullmeter-Movie_Lord-of-the-Rings_3",
      posterImage: "https://static.tildacdn.com/tild3663-3730-4631-a139-313736353636/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Harry-Potter": [
    {
      nameRu: "Философский камень || Гарри Поттер",
      nameEn: "Sorcerer’s Stone || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239738?t=1m32s"],
      id: "Fullmeter-Movie_Harry-Potter_1",
      posterImage: "https://static.tildacdn.com/tild3231-3535-4861-a133-333534643364/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тайная комната || Гарри Поттер",
      nameEn: "Chamber of Secrets || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239739"],
      id: "Fullmeter-Movie_Harry-Potter_2",
      posterImage: "https://static.tildacdn.com/tild3261-3032-4035-b662-396163663539/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Узник Азкабана || Гарри Поттер",
      nameEn: "Prisoner of Azkaban || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239753?t=4h48m33s"],
      id: "Fullmeter-Movie_Harry-Potter_3",
      posterImage: "https://static.tildacdn.com/tild6139-6533-4334-a233-303439356333/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Кубок огня || Гарри Поттер",
      nameEn: "Goblet of Fire || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239769?t=5m0s"],
      id: "Fullmeter-Movie_Harry-Potter_4",
      posterImage: "https://static.tildacdn.com/tild3539-3065-4934-b137-363565663935/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Орден Феникса || Гарри Поттер",
      nameEn: "Order of the Phoenix || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239770?t=1m56s"],
      id: "Fullmeter-Movie_Harry-Potter_5",
      posterImage: "https://static.tildacdn.com/tild3839-3165-4431-b362-663132383434/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Принц-полукровка || Гарри Поттер",
      nameEn: "Half-Blood Prince || Harry Potter",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239770?t=2h51m0s"],
      id: "Fullmeter-Movie_Harry-Potter_6",
      posterImage: "https://static.tildacdn.com/tild3130-3030-4261-b433-333137646636/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дары Смерти: Часть I || Гарри Поттер",
      nameEn: "Deathly Hallows: Part 1 || Harry Potter",
      titleLink: ["boosty", "hiddenarchive/posts/c8d61c63-0c27-4f7b-a579-a7cfb0b8a647?share=post_link"],
      id: "Fullmeter-Movie_Harry-Potter_7",
      posterImage: "https://static.tildacdn.com/tild3336-3664-4831-a336-366534666439/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дары Смерти: Часть II || Гарри Поттер",
      nameEn: "Deathly Hallows: Part 2 || Harry Potter",
      titleLink: ["boosty", "hiddenarchive/posts/36c09fbf-534b-438b-bb69-23b7adcf54cc?share=post_link"],
      id: "Fullmeter-Movie_Harry-Potter_8",
      posterImage: "https://static.tildacdn.com/tild3333-6239-4361-b163-643565333561/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_The-Hunger-Games": [
    {
      nameRu: "Голодные игры",
      nameEn: "The Hunger Games",
      titleLink: ["boosty", "hiddenarchive/posts/bcf8e22d-6125-4d1a-b072-98061aa76d53?share=post_link"],
      id: "Fullmeter-Movie_The-Hunger-Games_1",
      posterImage: "https://static.tildacdn.com/tild3361-6161-4261-a134-616361346363/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "И вспыхнет пламя || Голодные игры",
      nameEn: "Catching Fire || The Hunger Games",
      titleLink: ["boosty", "hiddenarchive/posts/91e9f948-3cce-4291-88f4-c6676638ceda?share=post_link"],
      id: "Fullmeter-Movie_The-Hunger-Games_2",
      posterImage: "https://static.tildacdn.com/tild3264-3962-4662-b432-323632623135/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Сойка-пересмешница. Часть 1 || Голодные игры",
      nameEn: "Mockingjay – Part 1 || The Hunger Games",
      titleLink: ["boosty", "hiddenarchive/posts/7f97365d-ce93-45a3-964b-c61a5fdefeb3?share=post_link"],
      id: "Fullmeter-Movie_The-Hunger-Games_3",
      posterImage: "https://static.tildacdn.com/tild3764-6635-4133-a531-313238393062/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Сойка-пересмешница. Часть 2 || Голодные игры",
      nameEn: "Mockingjay – Part 2 || The Hunger Games",
      titleLink: ["boosty", "hiddenarchive/posts/b6d173b0-f2db-42ff-821b-3685ffad6568?share=post_link"],
      id: "Fullmeter-Movie_The-Hunger-Games_4",
      posterImage: "https://static.tildacdn.com/tild6531-3836-4665-b362-306664643865/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_John-Wick": [
    {
      nameRu: "Джон Уик",
      nameEn: "John Wick",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240007?t=8h57m31s"],
      id: "Fullmeter-Movie_John-Wick-1",
      posterImage: "https://static.tildacdn.com/tild3263-3766-4066-a265-366264633235/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Джон Уик 2",
      nameEn: "John Wick: Chapter 2",
      titleLink: ["boosty", "hiddenarchive/posts/449ba465-31b5-41b8-b8a3-a03d094813c4?share=post_link"],
      id: "Fullmeter-Movie_John-Wick-2",
      posterImage: "https://static.tildacdn.com/tild3063-6430-4665-a462-323133633635/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Джон Уик 3",
      nameEn: "John Wick: Chapter 3 – Parabellum",
      titleLost: "lost",
      id: "Fullmeter-Movie_John-Wick-3",
      posterImage: "https://static.tildacdn.com/tild3866-3836-4535-b966-653762323834/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Джон Уик 4",
      nameEn: "John Wick: Chapter 4",
      titleLink: ["boosty", "hiddenarchive/posts/ee52e19a-5adb-45dc-98fd-b35d38b4c522?share=post_link"],
      id: "Fullmeter-Movie_John-Wick-4",
      posterImage: "https://static.tildacdn.com/tild3436-6166-4561-b361-313731656662/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Dune": [
    {
      nameRu: "Часть первая || Дюна",
      nameEn: "Part One || Dune",
      titleLink: ["boosty", "hiddenarchive/posts/844c8155-3447-4fa7-9d43-7e4aac93da01?share=post_link"],
      id: "Fullmeter-Movie_Dune-1",
      posterImage: "https://static.tildacdn.com/tild3237-6465-4233-b735-343339303034/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Часть вторая || Дюна",
      nameEn: "Part Two || Dune",
      titleLink: ["boosty", "hiddenarchive/posts/9d538783-01c2-49b2-a6f2-19746575af30?share=post_link"],
      id: "Fullmeter-Movie_Dune-2",
      posterImage: "https://static.tildacdn.com/tild3763-6331-4238-a438-653136303933/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Conjuring": [
    {
      nameRu: "Заклятие",
      nameEn: "The Conjuring",
      titleLink: ["vk", "video-208448461_456239247?t=10m22s"],
      id: "Fullmeter-Movie_Conjuring-1",
      posterImage: "https://static.tildacdn.com/tild6264-3937-4636-b130-363666623562/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Заклятие 2",
      nameEn: "The Conjuring 2",
      titleLink: ["vk", "video-208448461_456239246?t=6m34s"],
      id: "Fullmeter-Movie_Conjuring-2",
      posterImage: "https://static.tildacdn.com/tild3632-6262-4265-b466-383230383761/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Заклятие",
      nameEn: "The Conjuring",
      titleStatus: "Пересмотр",
      titleLink: ["vk", "video-208448461_456239245"],
      id: "Fullmeter-Movie_Conjuring-1-1",
      posterImage: "https://static.tildacdn.com/tild3766-3037-4334-b332-626436306638/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Заклятие",
      nameEn: "The Conjuring",
      titleStatus: "Пересмотр пересмотра",
      titleLink: ["vk", "video-208448461_456239483"],
      id: "Fullmeter-Movie_Conjuring-1-2",
      posterImage: "https://static.tildacdn.com/tild3266-6362-4431-b935-353634326337/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Star-Wars": [
    {
      nameRu: "Эпизод 1 – Скрытая угроза || Звёздные войны",
      nameEn: "Episode I – The Phantom Menace || Star Wars",
      titleLink: ["vk", "video-208448461_456239239"],
      id: "Fullmeter-Movie_Star-Wars-1",
      posterImage: "https://static.tildacdn.com/tild6561-3765-4336-a464-656136316563/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпизод 2 – Атака клонов || Звёздные войны",
      nameEn: "Episode II – Attack of the Clones || Star Wars",
      titleLink: ["boosty", "hiddenarchive/posts/ada10ee3-3ce0-4df0-9ed3-159122aa4b48?share=post_link"],
      id: "Fullmeter-Movie_Star-Wars-2",
      posterImage: "https://static.tildacdn.com/tild3434-6165-4433-b737-626636393937/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпизод 3 – Месть ситхов || Звёздные войны",
      nameEn: "Episode III – Revenge of the Sith || Star Wars",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239059?t=2h9m21s"],
      id: "Fullmeter-Movie_Star-Wars-3",
      posterImage: "https://static.tildacdn.com/tild3730-3332-4036-b365-333366663566/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпизод 4 – Новая надежда || Звёздные войны",
      nameEn: "Episode IV – A New Hope || Star Wars",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239338?t=3h55m3s"],
      id: "Fullmeter-Movie_Star-Wars-4",
      posterImage: "https://static.tildacdn.com/tild6139-3364-4239-b634-356135323537/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпизод 5 – Империя наносит ответный удар || Звёздные войны",
      nameEn: "Episode V – The Empire Strikes Back || Star Wars",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239420?t=7h31m40s"],
      id: "Fullmeter-Movie_Star-Wars-5",
      posterImage: "https://static.tildacdn.com/tild6339-3034-4061-b136-303539363030/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпизод 6 – Возвращение Джедая || Звёздные войны",
      nameEn: "Episode VI – Return of the Jedi || Star Wars",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239539?t=5h23m25s"],
      id: "Fullmeter-Movie_Star-Wars-6",
      posterImage: "https://static.tildacdn.com/tild3964-6537-4235-b231-323537626439/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Godfather": [
    {
      nameRu: "Крёстный отец",
      nameEn: "The Godfather: Part I",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241445?t=15m32s"],
      id: "Fullmeter-Movie_Godfather-1",
      posterImage: "https://static.tildacdn.com/tild3030-3465-4761-b263-376363623162/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Крёстный отец 2",
      nameEn: "The Godfather: Part II",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241488?t=8h17m15s"],
      id: "Fullmeter-Movie_Godfather-2",
      posterImage: "https://static.tildacdn.com/tild6264-3632-4563-b931-366362373764/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Крёстный отец 3",
      nameEn: "The Godfather: Part III",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241636?t=12m48s"],
      id: "Fullmeter-Movie_Godfather-3",
      posterImage: "https://static.tildacdn.com/tild3938-6362-4363-a233-383336666431/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Scream": [
    {
      nameRu: "Крик",
      nameEn: "Scream",
      titleLink: ["boosty", "hiddenarchive/posts/887f3869-49a6-484a-9644-7b896f8daac2?share=post_link"],
      id: "Fullmeter-Movie_Scream-1",
      posterImage: "https://static.tildacdn.com/tild3538-3037-4838-b635-613238333564/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Крик",
      nameEn: "Scream",
      titleStatus: "Пересмотр",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239485?t=1h33m27s"],
      id: "Fullmeter-Movie_Scream-1-1",
      posterImage: "https://static.tildacdn.com/tild3734-6464-4637-b333-396634363462/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Крик",
      nameEn: "Scream",
      titleStatus: "Пересмотр пересмотра",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239986?t=8h25m32s"],
      id: "Fullmeter-Movie_Scream-1-2",
      posterImage: "https://static.tildacdn.com/tild3233-6236-4534-a662-373762613266/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Hangover": [
    {
      nameRu: "Мальчишник в Вегасе",
      nameEn: "The Hangover",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240602?t=2h23m20s"],
      id: "Fullmeter-Movie_Hangover-1",
      posterImage: "https://static.tildacdn.com/tild3631-3431-4431-a134-656531613933/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Из Вегаса в Бангкок || Мальчишник в Вегасе",
      nameEn: "The Hangover Part II",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240602?t=4h32m20s"],
      id: "Fullmeter-Movie_Hangover-2",
      posterImage: "https://static.tildacdn.com/tild3334-6564-4532-a635-623266373638/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мальчишник: Часть 3 || Мальчишник в Вегасе",
      nameEn: "The Hangover Part III",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240774?t=1m40s"],
      id: "Fullmeter-Movie_Hangover-3",
      posterImage: "https://static.tildacdn.com/tild3561-3632-4163-b538-663539633038/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Marvel-Cinematic-Universe": [
    {
      nameRu: "Железный человек || Марвел",
      nameEn: "Iron Man || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239081?t=4h30m1s"],
      id: "Fullmeter-Movie_MCU-Iron-Man",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Первый мститель || Марвел",
      nameEn: "Captain America: The First Avenger || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239101?t=6h14m53s"],
      id: "Fullmeter-Movie_MCU-Captain-America",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тор || Марвел",
      nameEn: "Thor || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239179?t=5h53m36s"],
      id: "Fullmeter-Movie_MCU-Thor",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Железный человек 2 || Марвел",
      nameEn: "Iron Man 2 || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239201?t=20m22s"],
      id: "Fullmeter-Movie_MCU-Iron-Man-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мстители || Марвел",
      nameEn: "The Avengers || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239201?t=2h55m1s"],
      id: "Fullmeter-Movie_MCU-The-Avengers",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Железный человек 3 || Марвел",
      nameEn: "Iron Man 3 || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239339?t=2h7m29s"],
      id: "Fullmeter-Movie_MCU-Iron-Man-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тор 2: Царство тьмы || Марвел",
      nameEn: "Thor: The Dark World || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239345?t=2h26m33s"],
      id: "Fullmeter-Movie_MCU-Thor-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Первый мститель 2: Другая война || Марвел",
      nameEn: "Captain America: The Winter Soldier || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239464?t=4h29m31s"],
      id: "Fullmeter-Movie_MCU-Captain-America-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мстители 2: Эра Альтрона || Марвел",
      nameEn: "Avengers: Age of Ultron || Marvel",
      titleLink: ["vk", "video-208448461_456239469"],
      id: "Fullmeter-Movie_MCU-Avengers-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-муравей || Марвел",
      nameEn: "Ant-Man || Marvel",
      titleLink: ["vk", "video-208448461_456239472"],
      id: "Fullmeter-Movie_MCU-Ant-Man",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Первый мститель 3: Противостояние || Марвел",
      nameEn: "Captain America: Civil War || Marvel",
      titleLink: ["vk", "video-208448461_456239479"],
      id: "Fullmeter-Movie_MCU-Captain-America-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Доктор Стрэндж || Марвел",
      nameEn: "Doctor Strange || Marvel",
      titleLink: ["boosty", "hiddenarchive/posts/43da4d10-4533-46e9-98a1-32fcf4d37bcc?share=post_link"],
      id: "Fullmeter-Movie_MCU-Doctor-Strange",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Стражи Галактики || Марвел",
      nameEn: "Guardians of the Galaxy Vol.1 || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239038?t=4h44m56s"],
      id: "Fullmeter-Movie_MCU-Guardians-of-the-Galaxy",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Стражи Галактики 2 || Марвел",
      nameEn: "Guardians of the Galaxy Vol.2 || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239065?t=7h39m25s"],
      id: "Fullmeter-Movie_MCU-Guardians-of-the-Galaxy-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-паук: Возвращение домой || Марвел",
      nameEn: "Spider-Man: Homecoming || Marvel",
      titleLink: ["boosty", "hiddenarchive/posts/da5e8df2-f921-401b-b38c-8fa39fac2fb8?share=post_link"],
      id: "Fullmeter-Movie_MCU-Spider-Man-Homecoming",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тор 3: Рагнарёк || Марвел",
      nameEn: "Thor: Ragnarok || Marvel",
      titleLink: ["vk", "video-208448461_456239544"],
      id: "Fullmeter-Movie_MCU-Thor-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чёрная пантера || Марвел",
      nameEn: "Black Panther || Marvel",
      titleLink: ["vk", "video-208448461_456239547?t=9m58s"],
      id: "Fullmeter-Movie_MCU-Black-Panther",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мстители 3: Война бесконечности || Марвел",
      nameEn: "Avengers: Infinity War || Marvel",
      titleLink: ["vk", "video-208448461_456239560"],
      id: "Fullmeter-Movie_MCU-Avengers-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-муравей и Оса || Марвел",
      nameEn: "Ant-Man and the Wasp || Marvel",
      titleLink: ["vk", "video-208448461_456239563"],
      id: "Fullmeter-Movie_MCU-Ant-Man-and-the-Wasp",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Капитан Марвел || Марвел",
      nameEn: "Captain Marvel || Marvel",
      titleLink: ["vk", "video-208448461_456239577"],
      id: "Fullmeter-Movie_MCU-Captain-Marvel",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мстители 4: Финал || Марвел",
      nameEn: "Avengers: Endgame || Marvel",
      titleLink: ["vk", "video-208448461_456239580"],
      id: "Fullmeter-Movie_MCU-Avengers-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    { pasteCard: "Series-Serials_Loki" },
    {
      nameRu: "Человек-паук || Марвел",
      nameEn: "Spider-Man || Marvel",
      titleLink: ["vk", "video-208448461_456239500"],
      id: "Fullmeter-Movie_MCU-Spider-Man-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-паук 2 || Марвел",
      nameEn: "Spider-Man 2 || Marvel",
      titleLink: ["vk", "video-208448461_456239581"],
      id: "Fullmeter-Movie_MCU-Spider-Man-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-паук 3: Враг в отражении || Марвел",
      nameEn: "Spider-Man 3 || Marvel",
      titleLink: ["boosty", "hiddenarchive/posts/92a3b3d4-c625-40a0-9903-daf54d9a03ed?share=post_link"],
      id: "Fullmeter-Movie_MCU-Spider-Man-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Новый Человек-паук || Марвел",
      nameEn: "The Amazing Spider-Man || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239339?t=4h45m37s"],
      id: "Fullmeter-Movie_MCU-Amazing-Spider-Man-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Новый Человек-паук 2: Высокое напряжение || Марвел",
      nameEn: "The Amazing Spider-Man 2 || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239461?t=11m31s"],
      id: "Fullmeter-Movie_MCU-Amazing-Spider-Man-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Веном || Марвел",
      nameEn: "Venom || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239179?t=3h20m59s"],
      id: "Fullmeter-Movie_MCU-Venom",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-паук 2: Вдали от дома || Марвел",
      nameEn: "Spider-Man: Far from Home || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239608?t=12m30s"],
      id: "Fullmeter-Movie_MCU-Spider-Man-Far-from-Home",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Веном 2 || Марвел",
      nameEn: "Venom: Let There Be Carnage || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239617?t=12m25s"],
      id: "Fullmeter-Movie_MCU-Venom-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Человек-паук 3: Нет пути домой || Марвел",
      nameEn: "Spider-Man: No Way Home || Marvel",
      titleLink: ["vk", "video-208448461_456239624?t=33m38s"],
      id: "Fullmeter-Movie_MCU-Spider-Man-No-Way-Home",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    { pasteCard: "Series-Serials_WandaVision" },
    {
      nameRu: "Стражи Галактики: Праздничный спецвыпуск || Марвел",
      nameEn: "Guardians of the Galaxy Holiday Special || Marvel",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239737?t=1m3s"],
      id: "Fullmeter-Movie_MCU-Guardians-of-the-Galaxy-Special-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Шан-Чи и легенда десяти колец || Марвел",
      nameEn: "Shang-Chi and the Legend of the Ten Rings || Marvel",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240203"],
      id: "Fullmeter-Movie_MCU-Shang-Chi",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Доктор Стрэндж 2: В мультивселенной безумия || Марвел",
      nameEn: "Doctor Strange in the Multiverse of Madness || Marvel",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239881?t=3h13m50s"],
      id: "Fullmeter-Movie_MCU-Doctor Strange-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Вечные || Марвел",
      nameEn: "Eternals || Marvel",
      titleLink: ["vk", "video-208448461_456239603?t=12m14s"],
      id: "Fullmeter-Movie_MCU-Eternals",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    { pasteCard: "Series-Serials_Moon-Knight" },
    {
      nameRu: "Тор 4: Любовь и гром || Марвел",
      nameEn: "Thor: Love and Thunder || Marvel",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240030?t=3h54m47s"],
      id: "Fullmeter-Movie_MCU-Thor-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Стражи Галактики 3 || Марвел",
      nameEn: "Guardians of the Galaxy Vol.3 || Marvel",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241122?t=10m53s"],
      id: "Fullmeter-Movie_MCU-Guardians-of-the-Galaxy-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    { pasteCard: "Series-Cartoon_What-If" },
    { pasteCard: "Series-Serials_The-Falcon-and-the-Winter-Soldier" },
  ],
  "Fullmeter-Movie_Marvel-X-Men": [
    {
      nameRu: "Первый класс || Марвел Люди-Икс",
      nameEn: "First Class || Marvel X-Men",
      titleLink: ["vk", "video-208448461_456239468"],
      id: "Fullmeter-Movie_Marvel-X-Men-First-Class",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Начало. Росомаха || Марвел Люди-Икс",
      nameEn: "Origins: Wolverine || Marvel X-Men",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239697?t=2h7m30s"],
      id: "Fullmeter-Movie_Marvel-X-Men-Origins-Wolverine",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Люди Икс || Марвел Люди-Икс",
      nameEn: "X-Men || Marvel X-Men",
      titleLink: ["vk", "video-208448461_456239868"],
      id: "Fullmeter-Movie_Marvel-X-Men-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дэдпул || Марвел Люди-Икс",
      nameEn: "Deadpool || Marvel X-Men",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239192?t=8h42m44s"],
      id: "Fullmeter-Movie_Marvel-X-Men-Deadpool",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Люди Икс 2 || Марвел Люди-Икс",
      nameEn: "X2 || Marvel X-Men",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239728?t=6m54s"],
      id: "Fullmeter-Movie_Marvel-X-Men-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Последняя битва || Марвел Люди-Икс",
      nameEn: "The Last Stand || Marvel X-Men",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239742?t=5m0s"],
      id: "Fullmeter-Movie_Marvel-X-Men-The-Last-Stand",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Росомаха: Бессмертный || Марвел Люди-Икс",
      nameEn: "The Wolverine || Marvel X-Men",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239763?t=3m4s"],
      id: "Fullmeter-Movie_Marvel-X-Men-The-Wolverine",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дни минувшего будущего || Марвел Люди-Икс",
      nameEn: "Days of Future Past || Marvel X-Men",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239799?t=5h7m32s"],
      id: "Fullmeter-Movie_Marvel-X-Men-Days-of-Future-Past",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Логан || Марвел Люди-Икс",
      nameEn: "Logan || Marvel X-Men",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239902?t=9h43m48s"],
      id: "Fullmeter-Movie_Marvel-X-Men-Logan",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дэдпул 2 || Марвел Люди-Икс",
      nameEn: "Deadpool 2 || Marvel X-Men",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239930?t=15h48m50s"],
      id: "Fullmeter-Movie_Marvel-X-Men-Deadpool-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Дэдпул и Росомаха || Марвел Люди-Икс",
      nameEn: "Deadpool & Wolverine || Marvel X-Men",
      titleLink: ["boosty", "hiddenarchive/posts/d4ed6717-5899-438a-8b78-ebc9c3561f0a?share=success_publish_link"],
      id: "Fullmeter-Movie_Marvel-X-Men-Deadpool-Wolverine",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_The-Matrix": [
    {
      nameRu: "Матрица",
      nameEn: "The Matrix",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241643?t=6h36m16s"],
      id: "Fullmeter-Movie_The-Matrix-1",
      posterImage: "https://static.tildacdn.com/tild6364-3537-4961-b966-333764383236/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Перезагрузка || Матрица",
      nameEn: "Reloaded || The Matrix",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241645?t=13m3s"],
      id: "Fullmeter-Movie_The-Matrix-2",
      posterImage: "https://static.tildacdn.com/tild3564-3633-4463-a439-356562623936/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Революция || Матрица",
      nameEn: "Revolutions || The Matrix",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241659?t=10m35s"],
      id: "Fullmeter-Movie_The-Matrix-3",
      posterImage: "https://static.tildacdn.com/tild6163-6364-4838-b763-616537636464/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Back-to-the-Future": [
    {
      nameRu: "Назад в будущее",
      nameEn: "Back to the Future Part I",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240093?t=2h55m16s"],
      id: "Fullmeter-Movie_Back-to-the-Future-1",
      posterImage: "https://static.tildacdn.com/tild3332-3131-4037-a236-623764383561/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Назад в будущее 2",
      nameEn: "Back to the Future Part II",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240240?t=2h49m43s"],
      id: "Fullmeter-Movie_Back-to-the-Future-2",
      posterImage: "https://static.tildacdn.com/tild3633-3364-4136-a161-323538313635/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Назад в будущее 3",
      nameEn: "Back to the Future Part III",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240539"],
      id: "Fullmeter-Movie_Back-to-the-Future-3",
      posterImage: "https://static.tildacdn.com/tild6534-3165-4465-a466-663664303734/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Resident-Evil": [
    {
      nameRu: "Обитель зла",
      nameEn: "Resident Evil",
      titleLink: ["boosty", "hiddenarchive/posts/d7d330c4-9ab8-443f-afc3-85322f9f6b6a?share=success_publish_link"],
      id: "Fullmeter-Movie_Resident-Evil-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Апокалипсис || Обитель зла",
      nameEn: "Apocalypse || Resident Evil",
      titleLink: ["boosty", "hiddenarchive/posts/0bafa191-4e5a-43d0-9ff1-ea6f43b25a2c?share=success_publish_link"],
      id: "Fullmeter-Movie_Resident-Evil-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_The-Omen": [
    {
      nameRu: "Омен",
      nameEn: "The Omen",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241794?t=4h1m12s"],
      id: "Fullmeter-Movie_The-Omen-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Омен 2: Дэмиен",
      nameEn: "Damien: Omen II",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241815?t=15m57s"],
      id: "Fullmeter-Movie_The-Omen-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Омен 3: Последний конфликт",
      nameEn: "The Final Conflict",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241824?t=4h2m54s"],
      id: "Fullmeter-Movie_The-Omen-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_It": [
    {
      nameRu: "Оно",
      nameEn: "It",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239687?t=2h11m0s"],
      id: "Fullmeter-Movie_It-1",
      posterImage: "https://static.tildacdn.com/tild3766-3631-4661-b762-643431623137/img.webp",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Оно 2",
      nameEn: "It: Chapter Two",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239706?t=2h52m0s"],
      id: "Fullmeter-Movie_It-2",
      posterImage: "https://static.tildacdn.com/tild6363-6565-4331-b165-313863303439/img.webp",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Saw": [
    {
      nameRu: "Игра на выживание || Пила",
      nameEn: "Saw",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240016?t=8h11m0s"],
      id: "Fullmeter-Movie_Saw-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пила 2",
      nameEn: "Saw II",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240019?t=4h50m45s"],
      id: "Fullmeter-Movie_Saw-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пила 3",
      nameEn: "Saw III",
      titleLink: ["boosty", "godenname/posts/cb7f2fe7-2d62-4eec-9774-940e17f96b3b?t=8626&tmid=ece50ea5-0f98-4e8f-b653-04ab3b66aaa6"],
      id: "Fullmeter-Movie_Saw-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Kick-Ass": [
    {
      nameRu: "Пипец",
      nameEn: "Kick-Ass",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240721?t=5h42m"],
      id: "Fullmeter-Movie_Kick-Ass-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пипец 2",
      nameEn: "Kick-Ass 2",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240890?t=12m16s"],
      id: "Fullmeter-Movie_Kick-Ass-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Final-Destination": [
    {
      nameRu: "Пункт назначения",
      nameEn: "Final Destination",
      titleLink: ["boosty", "hiddenarchive/posts/74470363-5295-43e0-8a39-ee1024d6dfdf?share=post_link"],
      id: "Fullmeter-Movie_Final-Destination-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пункт назначения 2",
      nameEn: "Final Destination 2",
      titleLink: ["boosty", "hiddenarchive/posts/9af5fa4a-fee3-4e78-a61c-e59f92ecd0c8?share=post_link"],
      id: "Fullmeter-Movie_Final-Destination-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пункт назначения 3",
      nameEn: "Final Destination 3",
      titleLink: ["boosty", "hiddenarchive/posts/0bebee68-9214-4aa2-937b-8179aa612bd9?share=post_link"],
      id: "Fullmeter-Movie_Final-Destination-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пункт назначения 4",
      nameEn: "Final Destination 4",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239628"],
      id: "Fullmeter-Movie_Final-Destination-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пункт назначения 5",
      nameEn: "Final Destination 5",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239635"],
      id: "Fullmeter-Movie_Final-Destination-5",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Pirates-of-Caribbean": [
    {
      nameRu: "Проклятие Чёрной жемчужины || Пираты Карибского моря",
      nameEn: "The Curse of the Black Pearl || Pirates of the Caribbean",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240751?t=4s"],
      id: "Fullmeter-Movie_Pirates-of-Caribbean-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Сундук мертвеца || Пираты Карибского моря",
      nameEn: "Dead Man’s Chest || Pirates of the Caribbean",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240764"],
      id: "Fullmeter-Movie_Pirates-of-Caribbean-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "На краю света || Пираты Карибского моря",
      nameEn: "At World’s End || Pirates of the Caribbean",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240765"],
      id: "Fullmeter-Movie_Pirates-of-Caribbean-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "На странных берегах || Пираты Карибского моря",
      nameEn: "On Stranger Tides || Pirates of the Caribbean",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241448?t=12m22s"],
      id: "Fullmeter-Movie_Pirates-of-Caribbean-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мертвецы не рассказывают сказки || Пираты Карибского моря",
      nameEn: "Dead Men Tell No Tales || Pirates of the Caribbean",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241680?t=11m57s"],
      id: "Fullmeter-Movie_Pirates-of-Caribbean-5",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Twilight-Saga": [
    {
      nameRu: "Сумерки",
      nameEn: "Twilight",
      titleLink: ["boosty", "hiddenarchive/posts/efdc67c8-2be3-42b5-ab0f-7e3a2a9266b2?share=success_publish_link"],
      id: "Fullmeter-Movie_Twilight-Saga-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Новолуние || Сумерки",
      nameEn: "New Moon || Twilight",
      titleLink: ["boosty", "hiddenarchive/posts/0e37897e-c5bb-4e37-8a37-7cc7fa7739a7?share=success_publish_link"],
      id: "Fullmeter-Movie_Twilight-Saga-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Затмение || Сумерки",
      nameEn: "Eclipse || Twilight",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241272"],
      id: "Fullmeter-Movie_Twilight-Saga-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Рассвет: Часть 1 || Сумерки",
      nameEn: "Breaking Dawn – Part 1 || Twilight",
      titleLink: ["boosty", "hiddenarchive/posts/9ef9ed70-8dc2-4e81-8d00-89830deff6eb?share=success_publish_link"],
      id: "Fullmeter-Movie_Twilight-Saga-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Рассвет: Часть 2 || Сумерки",
      nameEn: "Breaking Dawn – Part 2 || Twilight",
      titleLost: "lost",
      id: "Fullmeter-Movie_Twilight-Saga-5",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Taxi": [
    {
      nameRu: "Такси",
      nameEn: "Taxi",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241433?t=24m25s"],
      id: "Fullmeter-Movie_Taxi-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Такси 2",
      nameEn: "Taxi 2",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241439?t=4h19m16s"],
      id: "Fullmeter-Movie_Taxi-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Такси 3",
      nameEn: "Taxi 3",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241449?t=14m19s"],
      id: "Fullmeter-Movie_Taxi-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Top-Gun": [
    {
      nameRu: "Лучший стрелок || Топ Ган",
      nameEn: "Top Gun",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239561?t=13m46s"],
      id: "Fullmeter-Movie_Top-Gun-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Мэверик || Топ Ган",
      nameEn: "Maverick || Top Gun",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239570?t=6h25m32s"],
      id: "Fullmeter-Movie_Top-Gun-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Transformers": [
    {
      nameRu: "Трансформеры",
      nameEn: "Transformers",
      titleLink: ["vk", "video-208448461_456239622"],
      id: "Fullmeter-Movie_Transformers-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Месть падших || Трансформеры",
      nameEn: "Revenge of the Fallen || Transformers",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239633?t=4h16m45s"],
      id: "Fullmeter-Movie_Transformers-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тёмная сторона Луны || Трансформеры",
      nameEn: "Dark of the Moon || Transformers",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239660?t=7h55m16s"],
      id: "Fullmeter-Movie_Transformers-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Последний рыцарь || Трансформеры",
      nameEn: "The Last Knight || Transformers",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239943?t=2h52m36s"],
      id: "Fullmeter-Movie_Transformers-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Эпоха истребления || Трансформеры",
      nameEn: "Age of Extinction || Transformers",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239953?t=2h18m41s"],
      id: "Fullmeter-Movie_Transformers-5",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Kill-Bill": [
    {
      nameRu: "Убить Билла",
      nameEn: "Kill Bill: Vol. 1",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239790?t=2h38m30s"],
      id: "Fullmeter-Movie_Kill-Bill-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Убить Билла 2",
      nameEn: "Kill Bill: Vol. 2",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239800?t=4h9m30s"],
      id: "Fullmeter-Movie_Kill-Bill-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_DC-Comics": [
    {
      seasonName: "Расширенная вселенная DC",
      items: [],
    },
    {
      nameRu: "Человек из стали || Супермен",
      nameEn: "Man of Steel || Superman",
      titleLink: ["boosty", "hiddenarchive/posts/87951db9-b7ab-42d5-9b81-2d3c66f3acd9?share=post_link"],
      id: "Fullmeter-Movie_DC-Comics-Man-of-Steel",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Бэтмен против Супермена: На заре справедливости",
      nameEn: "Batman v Superman: Dawn of Justice",
      titleLink: ["boosty", "hiddenarchive/posts/2ebf3cfc-8dc2-4a25-ac79-86ddd8e994f3?share=post_link"],
      id: "Fullmeter-Movie_DC-Comics-Dawn-of-Justice",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чудо-женщина",
      nameEn: "Wonder Woman",
      titleLink: ["boosty", "hiddenarchive/posts/59613fc1-ae23-473d-90a1-f2230e18a7c3?share=post_link"],
      id: "Fullmeter-Movie_DC-Comics-Wonder-Woman",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Лига справедливости Зака Снайдера",
      nameEn: "Zack Snyder's Justice League",
      titleLink: ["vk", "video-208448461_456239829"],
      id: "Fullmeter-Movie_DC-Comics-Zack-Snyder-Justice-League",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Отряд самоубийц: Миссия навылет",
      nameEn: "The Suicide Squad",
      titleLink: ["vk", "video-208448461_456239224"],
      id: "Fullmeter-Movie_DC-Comics-The-Suicide-Squad-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      seasonName: "Экранизации DC Comics",
      items: [],
    },
    {
      nameRu: "Бэтмен (1989)",
      nameEn: "Batman",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239059"],
      id: "Fullmeter-Movie_DC-Comics-Batman-1989",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Бэтмен (2022)",
      nameEn: "The Batman",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239017"],
      id: "Fullmeter-Movie_DC-Comics-Batman-2022",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Джокер",
      nameEn: "Joker",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239953?t=11h34m20s"],
      id: "Fullmeter-Movie_DC-Comics-Joker",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      seasonName: "Трилогия Кристофера Нолана",
      items: [],
    },
    {
      nameRu: "Бэтмен: Начало || Тёмный рыцарь",
      nameEn: "Batman Begins || The Dark Knight",
      titleLink: ["vk", "video-208448461_456240715"],
      id: "Fullmeter-Movie_DC-Comics-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тёмный рыцарь",
      nameEn: "The Dark Knight",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240728?t=2h2m30s"],
      id: "Fullmeter-Movie_DC-Comics-Dark-Knight-Rises",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Возрождение легенды || Тёмный рыцарь",
      nameEn: "The Dark Knight Rises || The Dark Knight",
      titleStatus: "Первая половина утеряна",
      titleLink: ["vk", "video-208448461_456240729?t=2m11s"],
      id: "Fullmeter-Movie_DC-Comics-Dark-Knight-Rises",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Fast-and-Furious": [
    {
      nameRu: "Форсаж",
      nameEn: "The Fast and the Furious",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240682?t=20m10s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Двойной форсаж",
      nameEn: "2 Fast 2 Furious",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240682?t=20m10s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Тройной форсаж: Токийский дрифт",
      nameEn: "The Fast and the Furious: Tokyo Drift",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240740?t=12m10s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Форсаж 4",
      nameEn: "Fast & Furious",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240808?t=12m15s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Форсаж 5",
      nameEn: "Fast Five",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240858?t=18m40s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Форсаж 6",
      nameEn: "Furious 6",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456240858?t=2h53m40s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Форсаж 7",
      nameEn: "Fast & Furious 7",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241174?t=12m22s"],
      id: "Fullmeter-Movie_Fast-and-Furious-",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Predator": [
    {
      nameRu: "Добыча || Хищник",
      nameEn: "Prey || Predator",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241147?t=12m48s"],
      id: "Fullmeter-Movie_Predator-0",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хищник",
      nameEn: "Predator",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241264?t=11m5s"],
      id: "Fullmeter-Movie_Predator-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хищник 2",
      nameEn: "Predator 2",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241485?t=6h12m44s"],
      id: "Fullmeter-Movie_Predator-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хищники",
      nameEn: "Predators",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241491?t=12m15s"],
      id: "Fullmeter-Movie_Predator-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хищник: Планета смерти",
      nameEn: "Predator: Badlands",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241748?t=2h22m4s"],
      id: "Fullmeter-Movie_Predator-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_The-Hobbit": [
    {
      nameRu: "Нежданное путешествие || Хоббит",
      nameEn: "An Unexpected Journey || The Hobbit",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239660?t=13m30s"],
      id: "Fullmeter-Movie_The-Hobbit-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Пустошь Смауга || Хоббит",
      nameEn: "The Desolation of Smaug || The Hobbit",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239681?t=3h58m40s"],
      id: "Fullmeter-Movie_The-Hobbit-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Битва пяти воинств || Хоббит",
      nameEn: "The Battle of the Five Armies || The Hobbit",
      donutTerms: "donut-lvl-1",
      titleLink: ["vk", "video-208448461_456239702?t=13m30s"],
      id: "Fullmeter-Movie_The-Hobbit-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Chronicles-of-Narnia": [
    {
      nameRu: "Лев, колдунья и волшебный шкаф || Хроники Нарнии",
      nameEn: "The Lion, The Witch and The Wardrobe || The Chronicles of Narnia",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241658?t=12m9s"],
      id: "Fullmeter-Movie_Chronicles-of-Narnia-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Принц Каспиан || Хроники Нарнии",
      nameEn: "Prince Caspian || The Chronicles of Narnia",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241674?t=3h31m17s"],
      id: "Fullmeter-Movie_Chronicles-of-Narnia-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Покоритель Зари || Хроники Нарнии",
      nameEn: "The Voyage of the Dawn Treader || The Chronicles of Narnia",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241692?t=4h21m45s"],
      id: "Fullmeter-Movie_Chronicles-of-Narnia-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Chronicles-of-Riddick": [
    {
      nameRu: "Кромешная тьма || Хроники Риддика",
      nameEn: "Pitch Black || The Chronicles of Riddick",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241777?t=12m0s"],
      id: "Fullmeter-Movie_Chronicles-of-Riddick-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хроники Риддика",
      nameEn: "The Chronicles of Riddick",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241781?t=4h39m37s"],
      id: "Fullmeter-Movie_Chronicles-of-Riddick-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Риддик || Хроники Риддика",
      nameEn: "Riddick || The Chronicles of Riddick",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241787?t=2h29m43s"],
      id: "Fullmeter-Movie_Chronicles-of-Riddick-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Halloween": [
    {
      nameRu: "Хэллоуин",
      nameEn: "Halloween",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239921?t=11m50s"],
      id: "Fullmeter-Movie_Halloween-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хэллоуин начинается",
      nameEn: "Halloween",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239921?t=2h22m15s"],
      id: "Fullmeter-Movie_Halloween-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хэллоуин убивает",
      nameEn: "Halloween Kills",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239921?t=4h34m4s"],
      id: "Fullmeter-Movie_Halloween-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Хэллоуин заканчивается",
      nameEn: "Halloween Ends",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239930?t=18h24m0s"],
      id: "Fullmeter-Movie_Halloween-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Rush-Hour": [
    {
      nameRu: "Час пик",
      nameEn: "Rush Hour",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241433?t=2h19m30s"],
      id: "Fullmeter-Movie_Rush-Hour-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Час пик 2",
      nameEn: "Rush Hour 2",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241439?t=2h19m35s"],
      id: "Fullmeter-Movie_Rush-Hour-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Alien": [
    {
      nameRu: "Прометей || Чужой",
      nameEn: "Prometheus || Alien",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241125?t=13m32s"],
      id: "Fullmeter-Movie_Alien-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Завет || Чужой",
      nameEn: "Covenant || Alien",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241126?t=14m1s"],
      id: "Fullmeter-Movie_Alien-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чужой",
      nameEn: "Alien",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241244?t=2h45m25s"],
      id: "Fullmeter-Movie_Alien-3",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чужие",
      nameEn: "Aliens",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241642?t=4h52m30s"],
      id: "Fullmeter-Movie_Alien-4",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чужой 3",
      nameEn: "Alien³",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241645?t=3h6m32s"],
      id: "Fullmeter-Movie_Alien-5",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Чужой 4",
      nameEn: "Resurrection || Alien",
      donutTerms: "donut-lvl-3",
      titleLink: ["vk", "video-208448461_456241653?t=10m15s"],
      id: "Fullmeter-Movie_Alien-6",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Chapiteau-Show": [
    {
      nameRu: "Любовь и дружба || Шапито-шоу",
      titleLink: ["boosty", "godenname/posts/6e76643e-b5c9-45da-8ad1-b766ec0e419e?t=720&tmid=84f84d30-d826-4261-9b84-70a1d527db38"],
      id: "Fullmeter-Movie_Chapiteau-Show-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Уважение и сотрудничество || Шапито-шоу",
      titleLink: ["boosty", "godenname/posts/6e76643e-b5c9-45da-8ad1-b766ec0e419e?t=7413&tmid=84f84d30-d826-4261-9b84-70a1d527db38"],
      id: "Fullmeter-Movie_Chapiteau-Show-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Sherlock-Holmes": [
    {
      nameRu: "Шерлок Холмс",
      nameEn: "Sherlock Holmes",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239925?t=7h49m45s"],
      id: "Fullmeter-Movie_Sherlock-Holmes-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Игра теней || Шерлок Холмс",
      nameEn: "A Game of Shadows || Sherlock Holmes",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456239925?t=7h49m45s"],
      id: "Fullmeter-Movie_Sherlock-Holmes-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
  "Fullmeter-Movie_Ace-Ventura": [
    {
      nameRu: "Розыск домашних животных || Эйс Вентура",
      nameEn: "Pet Detective",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240685?t=0s"],
      id: "Fullmeter-Movie_Ace-Ventura-1",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
    {
      nameRu: "Когда зовёт природа || Эйс Вентура",
      nameEn: "When Nature Calls || Ace Ventura",
      donutTerms: "donut-lvl-2",
      titleLink: ["vk", "video-208448461_456240685?t=0s"],
      id: "Fullmeter-Movie_Ace-Ventura-2",
      posterImage: "",
      cardType: "fullmeter-Movie",
    },
  ],
};
